global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'homelab'
    environment: 'prod'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

scrape_configs:
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # Enterprise pattern: File-based service discovery
  - job_name: 'infrastructure'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/infrastructure/*.yml'
        refresh_interval: 30s
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'applications'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/applications/*.yml'
        refresh_interval: 30s
    scrape_interval: 15s
    metrics_path: /metrics
