# Node Exporter for core VM
- targets:
    - 'prod-core-01:9100'
  labels:
    host: 'core-vm'
    service: 'node-exporter'
    component: 'system-metrics'
    environment: 'homelab'
    team: 'sre'

# cAdvisor for core VM
- targets:
    - 'prod-core-01:8083'
  labels:
    host: 'core-vm'
    service: 'cadvisor'
    component: 'container-metrics'
    environment: 'homelab'
    team: 'sre'
