# ================================
# Node Exporter (System Metrics)
# ================================

groups:
  - name: node-exporter-system
    rules:
      # Example: alert if CPU usage > 90% for 5 minutes
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance)(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 90% for more than 5 minutes."

      # Example: alert if available memory < 10%
      - alert: LowMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low available memory on {{ $labels.instance }}"
          description: "Available memory is below 10% for more than 5 minutes."

# ================================
# cAdvisor (Container Metrics)
# ================================

  - name: cadvisor-container
    rules:
      # Example: alert if container CPU usage > 80% for 5 minutes
      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage in container on {{ $labels.instance }}"
          description: "A container is using more than 80% CPU for 5 minutes."

      # Example: alert if container memory usage > 90%
      - alert: ContainerHighMemory
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage in container on {{ $labels.instance }}"
          description: "A container is using more than 90% of its memory limit."
